Rdm 10876
hmcts/aac-manage-case-assignment pull request #216
Opened 2021-01-28 10:02 UTC by tomxelliott

**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link (if applicable) ###

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2021-02-01 11:21 UTC, MSancaktutar approved these changes
LGTM

2021-02-01 11:27 UTC, smathangi commented on src/integrationTest/java/uk/gov/hmcts/reform/managecase/repository/DefinitionStoreRepositoryIT.java
> +        assertNotNull(cacheManager.getCache("challengeQuestions").getNativeCache());
could you assert number of calls it's making to definitionStoreApiClient for each cache hit/miss

2021-02-01 11:28 UTC, smathangi commented on src/main/java/uk/gov/hmcts/reform/managecase/repository/CaseTypeDefinitionVersion.java
> +@Setter
no need of additional @Getter and @Setter

2021-02-01 11:30 UTC, smathangi commented on src/main/java/uk/gov/hmcts/reform/managecase/repository/DefaultDefinitionStoreRepository.java
> +        key = "{#caseTypeId, #userId, #jurisdiction, #root.target.getLatestVersion(#caseTypeId)}")
Can you remove userId and Jurisdiction form key please (at least userId). Otherwise this cache wouldn't be useful much.

2021-02-01 11:34 UTC, smathangi commented on src/main/java/uk/gov/hmcts/reform/managecase/service/noc/NoticeOfChangeQuestions.java
> +                .questionText(challengeQuestion.getQuestionText())
IMO a separate response class without answer fields better. (separation of layers)
Or move this logic to a method in ChallengeQuestion class #cloneWithoutAnswers(ChallengeQuestion challengeQuestion)

2021-02-01 11:45 UTC, MSancaktutar requested changes
Sorry, I happened to miss a few important points @smathangi nicely pointed out, particularly about the cache key structure. So, kindly requesting them to be addressed.

2021-02-02 00:11 UTC, MSancaktutar approved these changes
Good to go.

2021-02-05 14:55 UTC, smathangi approved these changes

2021-02-09 10:22 UTC, merged