MCA setup improvements
hmcts/aac-manage-case-assignment pull request #81
Opened 2020-08-17 10:51 UTC by smathangi

**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link (if applicable) ###

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2020-09-04 11:27 UTC, mattnayler requested changes
Works for me locally: 👍  but see minor changes in comments.

2020-09-04 11:27 UTC, mattnayler commented on aca-docker/bin/set-environment-variables.sh
> +                $command
If this fails on EVs that have spaces in values : would switching to `source ./aca-docker/bin/env_variables_all.txt ` work either in this script or as an alternative to it?  (if so update script and/or README)

2020-09-07 11:11 UTC, mattnayler approved these changes
👍  LGTM: under assumption that switch to an update `befta_fw` which resolves AAT callback issues is also included.

2020-09-09 07:54 UTC, MSancaktutar approved these changes
LGTM

2020-09-23 11:53 UTC, merged